In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import statsmodels.api as sm


In [3]:
raw_data = pd.read_csv('BankChurners.csv')
pd.set_option('max_columns',None)
raw_data.head()

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0  768805383  Existing Customer            45      M                3   
1  818770008  Existing Customer            49      F                5   
2  713982108  Existing Customer            51      M                3   
3  769911858  Existing Customer            40      F                4   
4  709106358  Existing Customer            40      M                3   

  Education_Level Marital_Status Income_Category Card_Category  \
0     High School        Married     $60K - $80K          Blue   
1        Graduate         Single  Less than $40K          Blue   
2        Graduate        Married    $80K - $120K          Blue   
3     High School        Unknown  Less than $40K          Blue   
4      Uneducated        Married     $60K - $80K          Blue   

   Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0              39                         5                       1   
1              44                         6                       1   
2              36                         4                       1   
3              34                         3                       4   
4              21                         5                       1   

   Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0                      3       12691.0                  777          11914.0   
1                      2        8256.0                  864           7392.0   
2                      0        3418.0                    0           3418.0   
3                      1        3313.0                 2517            796.0   
4                      0        4716.0                    0           4716.0   

   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
0                 1.335             1144              42                1.625   
1                 1.541             1291              33                3.714   
2                 2.594             1887              20                2.333   
3                 1.405             1171              20                2.333   
4                 2.175              816              28                2.500   

   Avg_Utilization_Ratio  \
0                  0.061   
1                  0.105   
2                  0.000   
3                  0.760   
4                  0.000   

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  \
0                                           0.000093                                                                                    
1                                           0.000057                                                                                    
2                                           0.000021                                                                                    
3                                           0.000134                                                                                    
4                                           0.000022                                                                                    

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  
0                                            0.99991                                                                                   
1                                            0.99994                                                                                   
2                                            0.99998                                                                                   
3                                            0.99987                                                                                   
4                                            0.99998

In [4]:
raw_data.describe(include = 'all')

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
count   1.012700e+04              10127  10127.000000  10127     10127.000000   
unique           NaN                  2           NaN      2              NaN   
top              NaN  Existing Customer           NaN      F              NaN   
freq             NaN               8500           NaN   5358              NaN   
mean    7.391776e+08                NaN     46.325960    NaN         2.346203   
std     3.690378e+07                NaN      8.016814    NaN         1.298908   
min     7.080821e+08                NaN     26.000000    NaN         0.000000   
25%     7.130368e+08                NaN     41.000000    NaN         1.000000   
50%     7.179264e+08                NaN     46.000000    NaN         2.000000   
75%     7.731435e+08                NaN     52.000000    NaN         3.000000   
max     8.283431e+08                NaN     73.000000    NaN         5.000000   

       Education_Level Marital_Status Income_Category Card_Category  \
count            10127          10127           10127         10127   
unique               7              4               6             4   
top           Graduate        Married  Less than $40K          Blue   
freq              3128           4687            3561          9436   
mean               NaN            NaN             NaN           NaN   
std                NaN            NaN             NaN           NaN   
min                NaN            NaN             NaN           NaN   
25%                NaN            NaN             NaN           NaN   
50%                NaN            NaN             NaN           NaN   
75%                NaN            NaN             NaN           NaN   
max                NaN            NaN             NaN           NaN   

        Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
count     10127.000000              10127.000000            10127.000000   
unique             NaN                       NaN                     NaN   
top                NaN                       NaN                     NaN   
freq               NaN                       NaN                     NaN   
mean         35.928409                  3.812580                2.341167   
std           7.986416                  1.554408                1.010622   
min          13.000000                  1.000000                0.000000   
25%          31.000000                  3.000000                2.000000   
50%          36.000000                  4.000000                2.000000   
75%          40.000000                  5.000000                3.000000   
max          56.000000                  6.000000                6.000000   

        Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
count            10127.000000  10127.000000         10127.000000   
unique                    NaN           NaN                  NaN   
top                       NaN           NaN                  NaN   
freq                      NaN           NaN                  NaN   
mean                 2.455317   8631.953698          1162.814061   
std                  1.106225   9088.776650           814.987335   
min                  0.000000   1438.300000             0.000000   
25%                  2.000000   2555.000000           359.000000   
50%                  2.000000   4549.000000          1276.000000   
75%                  3.000000  11067.500000          1784.000000   
max                  6.000000  34516.000000          2517.000000   

        Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  \
count      10127.000000          10127.000000     10127.000000   
unique              NaN                   NaN              NaN   
top                 NaN                   NaN              NaN   
freq                NaN                   NaN              NaN   
mean        7469.139637              0.759941      4404.086304   
std         9090.685324              0.219207      3397.129

In [6]:
data = raw_data.drop('CLIENTNUM', axis=1)

Take a look on the Attrition_Flag to see how many percent of churn rate here.

In [12]:
data = data.drop(data.columns[[20,21]],axis = 1)

In [14]:
data['Attrition_Flag']=data['Attrition_Flag'].map({'Existing Customer':1,'Attrited Customer':0})

Create a more readerable data and convert all categorical variable to numeric

In [15]:
data['Gender']=data['Gender'].map({'M':1,'F':0})

In [16]:
data.Card_Category.unique()

array(['Blue', 'Gold', 'Silver', 'Platinum'], dtype=object)

In [17]:
data.Marital_Status.unique()

array(['Married', 'Single', 'Unknown', 'Divorced'], dtype=object)

In [18]:
data.Education_Level.unique()

array(['High School', 'Graduate', 'Uneducated', 'Unknown', 'College',
       'Post-Graduate', 'Doctorate'], dtype=object)

In [19]:
data['Marital_Status']=data['Marital_Status'].map({'Unknown':0,'Single':1,'Married':2,'Divorced':3})

In [20]:
data['Education_Level'] = data['Education_Level'].map({'Unknown':0,'Uneducated':1,'High School':2,'College':3,'Post-Graduate':4,'Graduate':5,'Doctorate':6})

In [21]:
data['Card_Category']=data['Card_Category'].map({'Blue':0,'Silver':1,'Gold':2,'Platinum':3})

In [23]:
data['Income_Category']=data['Income_Category'].map({'Unknown':0,'Less than $40K':1,'$40K - $60K':2,'$60K - $80K':3,'$80K - $120K':4,'$120K +':5})

In [24]:
data.head()

Attrition_Flag  Customer_Age  Gender  Dependent_count  Education_Level  \
0               1            45       1                3                2   
1               1            49       0                5                5   
2               1            51       1                3                5   
3               1            40       0                4                2   
4               1            40       1                3                1   

   Marital_Status  Income_Category  Card_Category  Months_on_book  \
0               2                3              0              39   
1               1                1              0              44   
2               2                4              0              36   
3               0                1              0              34   
4               2                3              0              21   

   Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0                         5                       1                      3   
1                         6                       1                      2   
2                         4                       1                      0   
3                         3                       4                      1   
4                         5                       1                      0   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0       12691.0                  777          11914.0                 1.335   
1        8256.0                  864           7392.0                 1.541   
2        3418.0                    0           3418.0                 2.594   
3        3313.0                 2517            796.0                 1.405   
4        4716.0                    0           4716.0                 2.175   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000

Declare targets and input

In [25]:
targets = data['Attrition_Flag']
inputs = data.drop(['Attrition_Flag'],axis = 1)

In [26]:
from sklearn.preprocessing import StandardScaler

Scaling as data normalization to treat the variable the same range

In [27]:
scaler = StandardScaler()
scaler.fit(inputs)
inputs_scaled = scaler.transform(inputs)

In [28]:
from sklearn.model_selection import train_test_split

Split dataset to train and test model, so that we can check the predictive potential of model

In [29]:
x_train, x_test, y_train, y_test = train_test_split(inputs_scaled, targets, test_size = 0.2, random_state=365)

In [30]:
x = sm.add_constant(x_train)
reg_log = sm.Logit(y_train,x)
results_log = reg_log.fit()

Optimization terminated successfully.
         Current function value: 0.232966
         Iterations 9


In [31]:
results_log.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:         Attrition_Flag   No. Observations:                 8101
Model:                          Logit   Df Residuals:                     8082
Method:                           MLE   Df Model:                           18
Date:                Fri, 25 Dec 2020   Pseudo R-squ.:                  0.4674
Time:                        16:48:19   Log-Likelihood:                -1887.3
converged:                       True   LL-Null:                       -3543.2
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.0349      0.069     43.993      0.000       2.900       3.170
x1             0.0830      0.069      1.206      0.228      -0.052       0.218
x2             0.4906      0.072      6.852      0.000       0.350       0.631
x3            -0.1817      0.043     -4.180      0.000      -0.267      -0.097
x4            -0.0078      0.042     -0.185      0.853      -0.090       0.075
x5             0.1309      0.043      3.034      0.002       0.046       0.215
x6            -0.2721      0.074     -3.695      0.000      -0.416      -0.128
x7            -0.1560      0.047     -3.354      0.001      -0.247      -0.065
x8             0.0266      0.068      0.388      0.698      -0.108       0.161
x9             0.7431      0.048     15.462      0.000       0.649       0.837
x10           -0.5074      0.043    -11.832      0.000      -0.591      -0.423
x11           -0.5495      0.045    -12.197      0.000      -0.638      -0.461
x12            0.1051   4.94e+06   2.13e-08      1.000   -9.68e+06    9.68e+06
x13            0.7852   4.43e+05   1.77e-06      1.000   -8.68e+05    8.68e+05
x14            0.0346   4.94e+06   7.01e-09      1.000   -9.68e+06    9.68e+06
x15            0.0664      0.045      1.477      0.140      -0.022       0.155
x16           -1.6339      0.087    -18.875      0.000      -1.804      -1.464
x17            2.7646      0.097     28.466      0.000       2.574       2.955
x18            0.6575      0.049     13.291      0.000       0.561       0.754
x19            0.0376      0.075      0.501      0.617      -0.110       0.185
==============================================================================
"""

This Model is much more better than the older => the left hand side independent variables play vital role in the prediction model. 

In [32]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
results_log.predict()

array([1.00, 1.00, 0.97, ..., 0.96, 1.00, 0.97])

In [33]:
np.array(data['Attrition_Flag'])

array([1, 1, 1, ..., 0, 0, 0])

In [34]:
results_log.pred_table()

array([[744.00, 541.00],
       [232.00, 6584.00]])

In [35]:
cm_df = pd.DataFrame(results_log.pred_table())
cm_df.columns = ['Predicted 0','Predicted 1']
cm_df = cm_df.rename(index={0: 'Actual 0',1:'Actual 1'})
cm_df

Predicted 0  Predicted 1
Actual 0        744.0        541.0
Actual 1        232.0       6584.0

In [36]:
cm = np.array(cm_df)
accuracy_train = (cm[0,0]+cm[1,1])/cm.sum()
accuracy_train

0.9045796815207999

Testing the model 

In [37]:
test_actual = y_test
test_data= sm.add_constant(x_test)

In [38]:
 def confusion_matrix(data,actual_values,model):
        pred_values = model.predict(data)
        bins=np.array([0,0.5,1])
        cm = np.histogram2d(actual_values, pred_values, bins=bins)[0]
        accuracy = (cm[0,0]+cm[1,1])/cm.sum()
        return cm, accuracy

In [39]:
# Create a confusion matrix with the test data
cm = confusion_matrix(test_data,test_actual,results_log)
cm

(array([[208.00, 134.00],
        [59.00, 1625.00]]),
 0.9047384007897334)

In [40]:
cm_df = pd.DataFrame(cm[0])
cm_df.columns = ['Predicted 0','Predicted 1']
cm_df = cm_df.rename(index={0: 'Actual 0',1:'Actual 1'})
cm_df

Predicted 0  Predicted 1
Actual 0        208.0        134.0
Actual 1         59.0       1625.0

In [41]:
# Check the missclassification rate
# Note that Accuracy + Missclassification rate = 1 = 100%
print ('Missclassification rate: '+str((1+1)/(208+134+59+1625)))

Missclassification rate: 0.0009871668311944718


The accuracy of model in predicting unchurned vs churned (with  18 variables) is 90.4%